#!/usr/bin/env bash

# Environment variables
export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
export __GL_SHADER_DISK_CACHE="1"
export __GL_SHADER_DISK_CACHE_PATH="$HOME/.local/share/Steam/steamapps/common/Umineko Golden Fantasia"
export WINEDEBUG="-all"
export DXVK_LOG_LEVEL="none"
export WINEARCH="win64"
export WINE="$(which wine)"
export WINE_MONO_CACHE_DIR="$HOME/.local/share/lutris/runners/wine/Proton 8.0/mono"
export WINE_GECKO_CACHE_DIR="$HOME/.local/share/lutris/runners/wine/Proton 8.0/gecko"
export WINEPREFIX="$HOME/ougon-wine-prefix"
export WINEESYNC="1"
export WINEFSYNC="1"
export WINE_FULLSCREEN_FSR="1"
export DXVK_NVAPIHACK="0"
export DXVK_ENABLE_NVAPI="1"
export PROTON_BATTLEYE_RUNTIME="$HOME/.local/share/lutris/runtime/battleye_runtime"
export PROTON_EAC_RUNTIME="$HOME/.local/share/lutris/runtime/eac_runtime"
export WINEDLLOVERRIDES="d3d9=n,b"
export STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.local/share/Steam/"
export STEAM_COMPAT_DATA_PATH="$HOME/.steam/steam/steamapps/compatdata/550340/pfx"
export STEAM_COMPAT_APP_ID="0"
export SteamAppId="0"
export SteamGameId="lutris-game"
export WINE_LARGE_ADDRESS_AWARE="1"
export TERM="xterm"
export DOTNET_ROOT=""

# Misc
export PROGRAM_FILES="$WINEPREFIX/drive_c/Program Files"
export RELOADED_DATA_PATH="$WINEPREFIX/drive_c/users/$USER/AppData/Roaming/Reloaded-Mod-Loader-II"
export X64DBG_PATH="$PROGRAM_FILES/x64dbg"
export GAME_PATH="$HOME/.local/share/Steam/steamapps/common/Umineko Golden Fantasia/Ougon.exe"
